In [1]:
import pandas as pd

df = pd.read_csv('all_recipes.csv')
df.head()

,calories,category,ingredients,ratings,recipe_id,reviews,title,total_mins,Season,DaytimeOfCooking,Veg/NonVeg
0,728,"['Desserts', 'Fruit Desserts', 'Pineapple Dess...","['2 cups all-purpose flour', '1 teaspoon salt'...",4.703704,263516,23,Chef John's Carrot Cake,95,Fall/Winter,Dessert,Non-Veg (Eggs)
1,692,"['Bread', 'Yeast Bread']","['1/2 cup warm milk', '1/3 cup warm water', '1...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,Any,Lunch/Dinner,Non-Veg (Cheese)
2,209,"['Soups, Stews and Chili', 'Stews', 'Beef']","['1 (1 1/2-pound) flank steak', '2 teaspoons k...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,Any,Dinner,Non-Veg (Beef)
3,505,"['Everyday Cooking', 'Vegetarian', 'Side Dishes']","['2 cups whole milk', '1 teaspoon kosher salt,...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,Any,Lunch/Dinner,Veg
4,291,"['Bread', 'Yeast Bread']","['1 cup warm water', '1 tablespoon white sugar...",5.000000,271049,4,Kouign-Amann,275,Any,Dessert,Non-Veg (Butter)

In [2]:
df2 = pd.read_csv('all_users.csv')
df2.head()

,date,rating,recipe_id,review,user_id,username
0,2012-09-11,5,222234,This recipe was delicious! Instead of cherry p...,3419993,Pie84
1,2012-12-25,5,222234,Made this recipe as instructed and it was easy...,3154459,hertzen
2,2012-11-22,5,222234,This was a great recipe to make using leftover...,10370475,suziloo
3,2015-07-07,5,222234,"Tasty , simple dessert that comes out cute as ...",2304335,Chelsea M.
4,2016-12-31,5,222234,"Delicious!! I was pressed for time, so I didn'...",1967176,Amanda H.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   calories          1175 non-null   object
 1   category          1163 non-null   object
 2   ingredients       1175 non-null   object
 3   ratings           1175 non-null   float64
 4   recipe_id         1175 non-null   int64
 5   reviews           1175 non-null   object
 6   title             1175 non-null   object
 7   total_mins        1175 non-null   int64
 8   Season            1163 non-null   object
 9   DaytimeOfCooking  1163 non-null   object
 10  Veg/NonVeg        1161 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 101.1+ KB

**DATA PRE-PROCESSING**

THIS INCLUDES DROPPING NULL ATTRIBUTES, DUPLICATE RECORDS ETC.
SEVERAL FEATURES LIKE CALORIES, CATEGORY, RATINGS, TOTAL_MINS WERE ALSO CONVERTED TO PROPER DATATYPE FOR MODEL TRAINING.

In [4]:
df.at[945, 'Veg/NonVeg'] = 'Non-Veg'
df.at[776, 'Veg/NonVeg'] = 'Non-Veg'

df = df.dropna()
df.drop_duplicates(inplace=True)
df = df.reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1162 entries, 0 to 1161
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   calories          1162 non-null   object
 1   category          1162 non-null   object
 2   ingredients       1162 non-null   object
 3   ratings           1162 non-null   float64
 4   recipe_id         1162 non-null   int64
 5   reviews           1162 non-null   object
 6   title             1162 non-null   object
 7   total_mins        1162 non-null   int64
 8   Season            1162 non-null   object
 9   DaytimeOfCooking  1162 non-null   object
 10  Veg/NonVeg        1162 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 100.0+ KB

In [5]:
#pre-processing the all_users.csv dataset
df2.dropna()
df2.drop_duplicates(inplace=True)
df2=df2.reset_index(drop=True)

def processing(value):
    return int(value)

df2['rating']=df2['rating'].apply(processing)
df2['recipe_id']=df2['recipe_id'].apply(processing)
df2['user_id']=df2['user_id'].apply(processing)

df2['date'] = pd.to_datetime(df2['date'], format='%Y-%m-%d')

In [6]:
#replacing the k in reviews to 1000s

def replace_k(value):
    if 'k' in value:
        value=str(value).split('k')
        value=value[0]
        value=float(value)*1000
    return value
df['reviews']=df['reviews'].apply(replace_k)

def cat_2(value):
    return eval(value)

df['category']=df['category'].apply(cat_2)
df['ingredients']=df['ingredients'].apply(cat_2)

df['reviews']=df['reviews'].apply(processing)

def calories(value):
    if value.isdigit():
        return int(value)
    else:
        return 1
df['calories']=df['calories'].apply(calories)

df.head()

,calories,category,ingredients,ratings,recipe_id,reviews,title,total_mins,Season,DaytimeOfCooking,Veg/NonVeg
0,728,"[Desserts, Fruit Desserts, Pineapple Desserts]","[2 cups all-purpose flour, 1 teaspoon salt, 1 ...",4.703704,263516,23,Chef John's Carrot Cake,95,Fall/Winter,Dessert,Non-Veg (Eggs)
1,692,"[Bread, Yeast Bread]","[1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,Any,Lunch/Dinner,Non-Veg (Cheese)
2,209,"[Soups, Stews and Chili, Stews, Beef]","[1 (1 1/2-pound) flank steak, 2 teaspoons kosh...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,Any,Dinner,Non-Veg (Beef)
3,505,"[Everyday Cooking, Vegetarian, Side Dishes]","[2 cups whole milk, 1 teaspoon kosher salt, or...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,Any,Lunch/Dinner,Veg
4,291,"[Bread, Yeast Bread]","[1 cup warm water, 1 tablespoon white sugar, 1...",5.000000,271049,4,Kouign-Amann,275,Any,Dessert,Non-Veg (Butter)

**CONVERTING SEASON, MEAL_TYPE AND DIET_TYPE FEATURES TO APPROPRIATE FORMAT**

In [7]:
df = df.rename(columns={'ratings': 'avg_rating', 'reviews':'no_reviews', 'Season':'season','DaytimeOfCooking':'meal_type','Veg/NonVeg':'diet_type'})
df.head()

,calories,category,ingredients,avg_rating,recipe_id,no_reviews,title,total_mins,season,meal_type,diet_type
0,728,"[Desserts, Fruit Desserts, Pineapple Desserts]","[2 cups all-purpose flour, 1 teaspoon salt, 1 ...",4.703704,263516,23,Chef John's Carrot Cake,95,Fall/Winter,Dessert,Non-Veg (Eggs)
1,692,"[Bread, Yeast Bread]","[1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,Any,Lunch/Dinner,Non-Veg (Cheese)
2,209,"[Soups, Stews and Chili, Stews, Beef]","[1 (1 1/2-pound) flank steak, 2 teaspoons kosh...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,Any,Dinner,Non-Veg (Beef)
3,505,"[Everyday Cooking, Vegetarian, Side Dishes]","[2 cups whole milk, 1 teaspoon kosher salt, or...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,Any,Lunch/Dinner,Veg
4,291,"[Bread, Yeast Bread]","[1 cup warm water, 1 tablespoon white sugar, 1...",5.000000,271049,4,Kouign-Amann,275,Any,Dessert,Non-Veg (Butter)

In [8]:
df['season'] = df['season'].apply(lambda x: x.split('/'))
df['season'] = df['season'].apply(lambda x: ['Summer', 'Spring', 'Fall', 'Winter'] if x == ['Any'] else x)
df['meal_type'] = df['meal_type'].apply(lambda x: x.split('/'))

**ADDING A NEW COLUMN 'NUMBER OF INGREDIENTS'**

THIS COULD BE INSIGHTFUL TO FIGURE OUT PROBABLE USER PREFERENCE TOWARDS SIMPLER RECIPES WITH LESS INGREDIENTS.

In [9]:
#added a column number of ingredients
def count_ingredients(ingredients):
    return len(ingredients)

# Apply the function to the 'ingredients' column and create a new column
df['no_ingredients'] = df['ingredients'].apply(count_ingredients)
df.head()

,calories,category,ingredients,avg_rating,recipe_id,no_reviews,title,total_mins,season,meal_type,diet_type,no_ingredients
0,728,"[Desserts, Fruit Desserts, Pineapple Desserts]","[2 cups all-purpose flour, 1 teaspoon salt, 1 ...",4.703704,263516,23,Chef John's Carrot Cake,95,"[Fall, Winter]",[Dessert],Non-Veg (Eggs),18
1,692,"[Bread, Yeast Bread]","[1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Non-Veg (Cheese),14
2,209,"[Soups, Stews and Chili, Stews, Beef]","[1 (1 1/2-pound) flank steak, 2 teaspoons kosh...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,"[Summer, Spring, Fall, Winter]",[Dinner],Non-Veg (Beef),24
3,505,"[Everyday Cooking, Vegetarian, Side Dishes]","[2 cups whole milk, 1 teaspoon kosher salt, or...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Veg,10
4,291,"[Bread, Yeast Bread]","[1 cup warm water, 1 tablespoon white sugar, 1...",5.000000,271049,4,Kouign-Amann,275,"[Summer, Spring, Fall, Winter]",[Dessert],Non-Veg (Butter),10

**TOKENIZATION OF TITLE COLUMN**

REMOVING OF STOP WORDS

STOP WORDS - those words that occur very frequently in a statement that provide no particular meaning for the ML model training. it is simply existing for grammatical uses like connectors, verbs etc.

eg. is, am, the, where, when, that, this etc.

REMOVING SPECIAL CHARACTERS

punctuations and other decorators were also removed for simplicity and accurate prediction of model.

In [10]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords 
titles = df['title']

def clean_text(text):

    text = text.lower()
    nopunct_text = ''.join([char for char in text if char.isalnum() or char.isspace()])
    tokens = word_tokenize(nopunct_text)
    return tokens

cleaned_titles = titles.apply(clean_text)
cleaned_titles

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[nltk_data] Downloading package punkt to
[nltk_data]     /home/swathidinesh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

0                  [chef, johns, carrot, cake]
1        [khachapuri, georgian, cheese, bread]
2                   [ropa, vieja, cuban, beef]
3                  [instant, mac, and, cheese]
4                                [kouignamann]
                         ...
1157             [bourbon, pepper, pan, sauce]
1158    [chef, johns, sweet, potato, biscuits]
1159                    [flax, seed, crackers]
1160                                [brandade]
1161                   [folded, pork, cutlets]
Name: title, Length: 1162, dtype: object

In [11]:
df['cleaned_title']=cleaned_titles
df.head()

,calories,category,ingredients,avg_rating,recipe_id,no_reviews,title,total_mins,season,meal_type,diet_type,no_ingredients,cleaned_title
0,728,"[Desserts, Fruit Desserts, Pineapple Desserts]","[2 cups all-purpose flour, 1 teaspoon salt, 1 ...",4.703704,263516,23,Chef John's Carrot Cake,95,"[Fall, Winter]",[Dessert],Non-Veg (Eggs),18,"[chef, johns, carrot, cake]"
1,692,"[Bread, Yeast Bread]","[1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Non-Veg (Cheese),14,"[khachapuri, georgian, cheese, bread]"
2,209,"[Soups, Stews and Chili, Stews, Beef]","[1 (1 1/2-pound) flank steak, 2 teaspoons kosh...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,"[Summer, Spring, Fall, Winter]",[Dinner],Non-Veg (Beef),24,"[ropa, vieja, cuban, beef]"
3,505,"[Everyday Cooking, Vegetarian, Side Dishes]","[2 cups whole milk, 1 teaspoon kosher salt, or...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Veg,10,"[instant, mac, and, cheese]"
4,291,"[Bread, Yeast Bread]","[1 cup warm water, 1 tablespoon white sugar, 1...",5.000000,271049,4,Kouign-Amann,275,"[Summer, Spring, Fall, Winter]",[Dessert],Non-Veg (Butter),10,[kouignamann]

In [12]:
import nltk
from nltk.stem import WordNetLemmatizer
import pandas as pd

nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

def lemmatize_dataframe_feature(df, feature_name):
    df[feature_name] = df[feature_name].apply(lambda row: lemmatize_list(row))
    return df

def lemmatize_list(list_of_strings):
    lemmatized_list = [lemmatizer.lemmatize(word) for word in list_of_strings]
    return lemmatized_list


data = lemmatize_dataframe_feature(df, 'cleaned_title')
print(data)

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/swathidinesh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

      calories                                        category  \
0          728  [Desserts, Fruit Desserts, Pineapple Desserts]
1          692                            [Bread, Yeast Bread]
2          209           [Soups, Stews and Chili, Stews, Beef]
3          505     [Everyday Cooking, Vegetarian, Side Dishes]
4          291                            [Bread, Yeast Bread]
...        ...                                             ...
1157       537      [Side Dish, Sauces and Condiments, Sauces]
1158       459                  [Bread, Quick Bread, Biscuits]
1159       104       [Appetizers and Snacks, Snacks, Crackers]
1160       105                [Appetizers and Snacks, Seafood]
1161       825            [Meat and Poultry, Pork, Tenderloin]

                                            ingredients  avg_rating  \
0     [2 cups all-purpose flour, 1 teaspoon salt, 1 ...    4.703704
1     [1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...    4.666667
2     [1 (1 1/2-pound) flank steak, 2 teaspoons kosh...    5.000000
3     [2 cups whole milk, 1 teaspoon kosher salt, or...    4.333333
4     [1 cup warm water, 1 tablespoon white sugar, 1...    5.000000
...                                                 ...         ...
1157  [2 (6 ounce) New York strip steaks, kosher sal...    5.000000
1158  [1 large orange-fleshed sweet potato, peeled, ...    4.666667
1159  [1 cup raw flax seeds, 3/4 teaspoon salt, 1/4 ...    3.777778
1160  [1 pound salted cod fish, 1 1/2 cups whole mil...    4.000000
1161  [1 (1 pound) pork tenderloin, trimmed, kosher ...    4.714286

      recipe_id  no_reviews                               title  total_mins  \
0        263516          23             Chef John's Carrot Cake          95
1        272625           2  Khachapuri (Georgian Cheese Bread)         115
2        272615           4             Ropa Vieja (Cuban Beef)         690
3        272461           9            "Instant" Mac and Cheese          28
4        271049           4                        Kouign-Amann         275
...         ...         ...                                 ...         ...
1157     265861           8            Bourbon Pepper Pan Sauce          25
1158     261792           2   Chef John's Sweet Potato Biscuits          40
1159     261801           8                  Flax Seed Crackers         680
1160     241556           8                            Brandade        1520
1161     270299           4                 Folded Pork Cutlets          50

                              season           meal_type  \
0                     [Fall, Winter]           [Dessert]
1     [Summer, Spring, Fall, Winter]     [Lunch, Dinner]
2     [Summer, Spring, Fall, Winter]            [Dinner]
3     [Summer, Spring, Fall, Winter]     [Lunch, Dinner]
4     [Summer, Spring, Fall, Winter]           [Dessert]
...                              ...                 ...
1157  [Summer, Spring, Fall, Winter]             [Sauce]
1158                  [Fall, Winter]  [Breakfast, Snack]
1159  [Summer, Spring, Fall, Winter]             [Snack]
1160  [Summer, Spring, Fall, Winter]         [Appetizer]
1161  [Summer, Spring, Fall, Winter]            [Dinner]

                    diet_type  no_ingredients  \
0              Non-Veg (Eggs)              18
1            Non-Veg (Cheese)              14
2              Non-Veg (Beef)              24
3                         Veg              10
4            Non-Veg (Butter)              10
...                       ...             ...
1157  Non-Veg (Optional Meat)              11
1158                      Veg              11
1159      Veg (Optional Seed)               6
1160            Non-Veg (Cod)              12
1161           Non-Veg (Pork)              11

                              cleaned_title
0                [chef, john, carrot, cake]
1     [khachapuri, georgian, cheese, bread]
2                [ropa, vieja, cuban, beef]
3               [instant, mac, and, cheese]
4                             [kouignamann]
...                                     ...
1157          [bourbon, pepper, pan, sauce]
1158   [chef, john, sweet, potato, biscuit]
1159                  [flax, seed, cracker]
1160                             [brandade]
1161                 [folded, pork, cutlet]

[1162 rows x 13 columns]

In [13]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemmatize_category_list(category_list):
    lemmatized_list = []
    for word in category_list:
        lemmatized_category = []
        
        lemmatized_category.append(lemmatizer.lemmatize(word.strip().lower()))
        lemmatized_list.append(lemmatized_category)
    return lemmatized_list

df['category_lemmatized'] = df['category'].apply(lemmatize_category_list)

print(df[['category', 'category_lemmatized']])

                                            category  \
0     [Desserts, Fruit Desserts, Pineapple Desserts]
1                               [Bread, Yeast Bread]
2              [Soups, Stews and Chili, Stews, Beef]
3        [Everyday Cooking, Vegetarian, Side Dishes]
4                               [Bread, Yeast Bread]
...                                              ...
1157      [Side Dish, Sauces and Condiments, Sauces]
1158                  [Bread, Quick Bread, Biscuits]
1159       [Appetizers and Snacks, Snacks, Crackers]
1160                [Appetizers and Snacks, Seafood]
1161            [Meat and Poultry, Pork, Tenderloin]

                                    category_lemmatized
0     [[dessert], [fruit desserts], [pineapple desse...
1                              [[bread], [yeast bread]]
2            [[soups, stews and chili], [stew], [beef]]
3     [[everyday cooking], [vegetarian], [side dishes]]
4                              [[bread], [yeast bread]]
...                                                 ...
1157    [[side dish], [sauces and condiments], [sauce]]
1158                [[bread], [quick bread], [biscuit]]
1159      [[appetizers and snacks], [snack], [cracker]]
1160               [[appetizers and snacks], [seafood]]
1161         [[meat and poultry], [pork], [tenderloin]]

[1162 rows x 2 columns]

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/swathidinesh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [14]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

def preprocess_ingredients(ingredients):

    ingredients=[ingredient.lower() for ingredient in ingredients]

    pattern=r'[^\w]'  # Matches any non-alphanumeric character
    ingredients=[re.sub(pattern, ' ', ingredient) for ingredient in ingredients]

    lemmatizer=WordNetLemmatizer()
    processed_ingredients=[[lemmatizer.lemmatize(word) for word in ingredients]]

    return processed_ingredients

ingre=df['ingredients'].apply(preprocess_ingredients)
ingre

0       [[2 cups all purpose flour, 1 teaspoon salt, 1...
1       [[1 2 cup warm milk, 1 3 cup warm water, 1 1 2...
2       [[1  1 1 2 pound  flank steak, 2 teaspoons kos...
3       [[2 cups whole milk, 1 teaspoon kosher salt  o...
4       [[1 cup warm water, 1 tablespoon white sugar, ...
                              ...
1157    [[2  6 ounce  new york strip steaks, kosher sa...
1158    [[1 large orange fleshed sweet potato  peeled,...
1159    [[1 cup raw flax seeds, 3 4 teaspoon salt, 1 4...
1160    [[1 pound salted cod fish, 1 1 2 cups whole mi...
1161    [[1  1 pound  pork tenderloin  trimmed, kosher...
Name: ingredients, Length: 1162, dtype: object

In [15]:
import re
from nltk.corpus import stopwords

stop_words = stopwords.words('english') 

def filter_custom_stop_words(data):
    new_stop_words =['taste','softened','teaspoon','teaspoons','tablespoons','cups','ounces','tablespoon',
                     'cup','ounce','pinch','salt','ground','large','finely','chopped','grated','optional',
                     'crushed','drained','divided','shredded','sliced','half','peeled','freshly','needed',
                     'frying','prepared','cut','small','cube','water','warm','ml','l','g','kg','mg','dl',
                     'gill','diced','pound','pint','quant','gallon','fl oz','°C','°F','taste']
    for i in new_stop_words:
        stop_words.append(i)
        
    filtered_data = []
    for recipe in data:
        sublist2 = []
        for sublist2_item in recipe:
            for i in sublist2_item:
                filtered_sublist3 = [word for word in i.split() if word not in stop_words and word.isalpha()]
                sublist2.append(filtered_sublist3)
        filtered_data.append(sublist2)
    return filtered_data

#function call for filtering
filtered_data = filter_custom_stop_words(ingre)

df['ingredients_filtered']=filtered_data
df.head()

,calories,category,ingredients,avg_rating,recipe_id,no_reviews,title,total_mins,season,meal_type,diet_type,no_ingredients,cleaned_title,category_lemmatized,ingredients_filtered
0,728,"[Desserts, Fruit Desserts, Pineapple Desserts]","[2 cups all-purpose flour, 1 teaspoon salt, 1 ...",4.703704,263516,23,Chef John's Carrot Cake,95,"[Fall, Winter]",[Dessert],Non-Veg (Eggs),18,"[chef, john, carrot, cake]","[[dessert], [fruit desserts], [pineapple desse...","[[purpose, flour], [], [baking, soda], [baking..."
1,692,"[Bread, Yeast Bread]","[1/2 cup warm milk, 1/3 cup warm water, 1 1/2 ...",4.666667,272625,2,Khachapuri (Georgian Cheese Bread),115,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Non-Veg (Cheese),14,"[khachapuri, georgian, cheese, bread]","[[bread], [yeast bread]]","[[milk], [], [white, sugar], [package, active,..."
2,209,"[Soups, Stews and Chili, Stews, Beef]","[1 (1 1/2-pound) flank steak, 2 teaspoons kosh...",5.000000,272615,4,Ropa Vieja (Cuban Beef),690,"[Summer, Spring, Fall, Winter]",[Dinner],Non-Veg (Beef),24,"[ropa, vieja, cuban, beef]","[[soups, stews and chili], [stew], [beef]]","[[flank, steak], [kosher], [black, pepper], [c..."
3,505,"[Everyday Cooking, Vegetarian, Side Dishes]","[2 cups whole milk, 1 teaspoon kosher salt, or...",4.333333,272461,9,"""Instant"" Mac and Cheese",28,"[Summer, Spring, Fall, Winter]","[Lunch, Dinner]",Veg,10,"[instant, mac, and, cheese]","[[everyday cooking], [vegetarian], [side dishes]]","[[whole, milk], [kosher], [cayenne, pepper], [..."
4,291,"[Bread, Yeast Bread]","[1 cup warm water, 1 tablespoon white sugar, 1...",5.000000,271049,4,Kouign-Amann,275,"[Summer, Spring, Fall, Winter]",[Dessert],Non-Veg (Butter),10,[kouignamann],"[[bread], [yeast bread]]","[[], [white, sugar], [active, dry, yeast], [br..."

In [16]:
df=df.drop(['title','category','ingredients'],axis=1)

In [17]:
def join_lists(data):

    joined_list = []
    for sublist in data:
        joined_list.append([' '.join(x) for x in sublist])  # Join elements with space
    return joined_list

# Join elements in each sublist
df['ingredients_filtered'] = join_lists(df['ingredients_filtered'])
df['category_lemmatized'] = join_lists(df['category_lemmatized'])
df['category_lemmatized']=df['category_lemmatized'].apply(lambda x: ', '.join(x))

for i in df['ingredients_filtered']:
    for j in i:
        if len(j)<1:
            i.remove(j)
            
def to_string(value):
    comb_str=' '.join(value)
    return comb_str

df['ingredients_filtered']=df['ingredients_filtered'].apply(to_string)
ingredients_filtered=df[['recipe_id','ingredients_filtered']]

**RECOMMENDATION BASED ON INGREDIENT SIMILARITY**

I DID THIS BY TAKING THE VECTOR FORMAT OF THE INGREDIENTS, CATEGORY AND TITLE COLUMN OF EACH RECIPE AND THEN FURTHER PLOTTING THE SIMILARITY BETWEEN EACH RECIPE USING COSINE SIMILARITY.
THIS IS DONE BY USING THE K-NEAREST NEIGHBOURS ALGORITHM. HERE K IS CHOSEN TO BE 10.


THIS MODEL SUGGESTS SIMILAR RECIPES WHEN ONE RECIPE IS VIEWED. THIS COULD GIVE OPTIONS FOR THE USER TO PICK.

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer=TfidfVectorizer()

df['combined_text'] = df['cleaned_title'].apply(' '.join) + ' ' + df['ingredients_filtered'] + ' ' + df['category_lemmatized']


recipe_text_features = vectorizer.fit_transform(df['combined_text'])

similarity=cosine_similarity(recipe_text_features, recipe_text_features)

similarity

array([[1.        , 0.11679077, 0.02704598, ..., 0.03257952, 0.00442233,
        0.03347495],
       [0.11679077, 1.        , 0.05286373, ..., 0.00880162, 0.03889843,
        0.21937197],
       [0.02704598, 0.05286373, 1.        , ..., 0.040295  , 0.11254314,
        0.06270797],
       ...,
       [0.03257952, 0.00880162, 0.040295  , ..., 1.        , 0.06596972,
        0.01784374],
       [0.00442233, 0.03889843, 0.11254314, ..., 0.06596972, 1.        ,
        0.04926132],
       [0.03347495, 0.21937197, 0.06270797, ..., 0.01784374, 0.04926132,
        1.        ]])

In [19]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(n_neighbors=10, algorithm='auto', metric='cosine')
knn.fit(recipe_text_features)

#function to recommend recipes based on KNN
def recommend_recipe(recipe_index):
    distances, indices = knn.kneighbors(recipe_text_features[recipe_index], n_neighbors=10)
    print(f"Recommendations for '{df['cleaned_title'][recipe_index]}':")
    for i in range(1, len(distances.flatten())):
        print(f"{df['recipe_id'][indices.flatten()[i]]}")

recommend_recipe(1)

Recommendations for '['khachapuri', 'georgian', 'cheese', 'bread']':
272625
256967
239148
232719
271049
271049
256997
264043
259099

In [20]:
import pickle
pickle.dump(recommend_recipe, open('knn_model.pkl','wb'))
loaded_recommend_recipes = pickle.load(open("knn_model.pkl", "rb"))
print(loaded_recommend_recipes(1))

Recommendations for '['khachapuri', 'georgian', 'cheese', 'bread']':
272625
256967
239148
232719
271049
271049
256997
264043
259099
None

In [21]:
df['ingredients_filtered'] = df['ingredients_filtered'].apply(lambda x: ''.join(x))
df['cleaned_title'] = df['cleaned_title'].apply(lambda x: ' '.join(x))

**MATRIX FACTORIZATION USING USER RATING AND COMBINATION OF INGREDIENTS,TITLE AND CATEGORY OF FOOD**

MATRIX FACTORIZATION IS COMMONLY USED FOR DETECTING A PATTERN BETWEEN DIFFERENT USERS AND THEIR INTEREST. SINCE WE HAVE DATASET OF USER RATING FOR DIFFERENT RECIPES, WE COULD PLOT USER VS. RECIPE MATRIX. THIS COULD SUGGEST RECIPES FOR A USER THAT WAS ACCEPTED BY A SIMILAR USER.

FOR THIS MODEL, THE INPUT IS USER_ID AND OUTPUT IS A SERIES OF RECIPE_ID'S

In [22]:
"""# Combining recipe attributes for TF-IDF
recipe_text_features=df[['ingredients_filtered', 'cleaned_title', 'category_lemmatized']]
recipe_text_features=' '.join(recipe_text_features)

#TF-IDF vectorization
recipe_features=vectorizer.fit_transform([recipe_text_features])
"""
#merge user and recipe datasets
user_recipe_df=df2.merge(df,on='recipe_id')

#user-recipe matrix
rating_matrix=user_recipe_df.pivot_table(values='rating',index='user_id',columns='recipe_id').fillna(0)
rating_matrix

recipe_id,219075,219076,219077,219078,219079,219082,219086,219088,219090,219091,...,272615,272625,272766,272767,272905,273034,273213,273285,273455,273495
user_id,,,,,,,,,,,,,,,,,,,,,
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
935,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25586309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25591130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25594700,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25595047,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25598991,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
from sklearn.decomposition import NMF

num_factors=10

#perform NMF Non-Negative Matrix Factorization
nmf = NMF(n_components=num_factors, random_state=42)
user_factors=nmf.fit_transform(rating_matrix)
recipe_factors=nmf.components_


def recommend_recipes(user_id, top_n=10):
    user_factor = user_factors[user_id]
    predicted_ratings = user_factor.dot(recipe_factors)
    top_recipe_indices = predicted_ratings.argsort()[-top_n:]
    recipe_ids = df['recipe_id'].iloc[top_recipe_indices] 
    return recipe_ids

#recommendations for user with ID 10
recommended_recipes=recommend_recipes(100)
print(recommended_recipes)

21     220127
248    238134
184    237499
161    220250
84     219919
82     219964
77     219091
79     222000
49     244979
23     239047
Name: recipe_id, dtype: int64

In [24]:
import pickle
pickle.dump(recommend_recipe, open('CF_model.pkl','wb'))
loaded_recommend_recipes = pickle.load(open("CF_model.pkl", "rb"))
print(loaded_recommend_recipes(100))

Recommendations for 'chef john irish pork stew':
234534
236603
235837
261441
245361
241310
268010
231009
221972
None

**ASSOCIATIVE RULE MINING - APRIORI ALGORITHM**

The Apriori algorithm is used to discover frequent itemsets in a dataset and extract association rules between items. The algorithm works by iteratively finding frequent itemsets of increasing lengths by applying a level-wise search strategy, based on the Apriori property, which states that any subset of a frequent itemset must also be frequent.

This strategy was used to find if complimentary food was chosen by users, based on the rating dataset.

here I filtered it out to user_id and list of recipe_id that got greater than 3 rating by them.

In [25]:
df_new = df2[['user_id', 'recipe_id','rating']]
df_new = df_new[(df_new['rating'] > 3)]
df_new.head()

    user_id  recipe_id  rating
0   3419993     222234       5
1   3154459     222234       5
2  10370475     222234       5
3   2304335     222234       5
4   1967176     222234       5

In [26]:
import pandas as pd

df_new = df_new[['user_id','recipe_id']]

grouped_data = df_new.groupby('user_id')['recipe_id'].apply(list).reset_index()

filtered_data = grouped_data[(grouped_data['recipe_id'].apply(len) > 1)]

filtered_data.columns = ['user_id', 'recipe_ids']

print(filtered_data)

        user_id                                         recipe_ids
1            39  [257938, 220126, 220181, 219966, 257179, 23170...
2           338                                   [239047, 221966]
17        11200                           [222187, 241001, 244200]
18        11687                                   [222187, 221054]
23        15720                                   [234534, 235613]
...         ...                                                ...
50946  25466173                                   [234534, 220059]
50951  25471109                                   [255591, 270676]
50977  25492240                   [222342, 231353, 261983, 231354]
51003  25534213                                   [219171, 234621]
51018  25557847                                   [220751, 219077]

[7536 rows x 2 columns]

In [27]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
import pandas as pd

data = grouped_data

te = TransactionEncoder()
te_ary = te.fit(data['recipe_id']).transform(data['recipe_id'])
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)

print("Frequent Itemsets:")
print(frequent_itemsets)

Frequent Itemsets:
Empty DataFrame
Columns: [support, itemsets]
Index: []